### ISSUE TITLE
Global kernel normalization is incorrect

### ISSUE THREAD

**Issue by bartolsthoorn** [cosmo-epfl/glosim2#3]
By default this the global kernel is not normalized, but enabling it currently does not do the correct normalization:
```python
def normalizeKernel(kernel):
    n,m = kernel.shape
    for it in range(n):
        for jt in range(m):
            kernel[it,jt] = kernel[it,jt] / np.sqrt(kernel[it,it]* kernel[jt,jt])
    return kernel
```

The problem is that `kernel[it,jt]` is in later loops used again as `kernel[jt,jt]`. This could be solved by keeping a copy of the diagonal.

**Comment by felixmusil** [comment]
Thank you for your observation. 
This function is unused so there are no problem here and I removed it now. Please have a look at global_kernel.py to find another version of this function.
